### ISSUE TITLE
Issue with integer partitions with 0 prefix

### ISSUE THREAD

**Issue by snarayananqubole** [facebook/presto#2233]
I have a partitioned table with integer part column type. The directory structure in S3 looks like this:
```
s3://bucket/table/day=06/hour=00/
s3://bucket/table/day=06/hour=01/
```
Partitioning columsn day and hour are both marked as integer type.

When I run a query against this table using Hive, all the data shows up properly. With Presto, I see zero rows. When I changed the partition column type to string, all the rows showed up.

**Comment by stagraqubole** [comment]
The problem happens when PredicatePushdown optimizer is called second time. First time it gets the correct partitions
list from HiveClient but stores it as casted values which drops the leading zeros. Second time around, it asks
HiveClient for partitions within the domain it had from first run which return no partitions.

To fix this, we modified HiveClient's getParitition method. It now in addition to asking metastore about partitions
with filters, also asks for all partitions if filtered version returned empty list and then filters the returned list by the predicate.

**Comment by nezihyigitbasi** [comment]
@stagraqubole thanks a lot for opening this issue, really curious to see the PR. 

We worked around this issue by updating the partition names to remove the leading zeros. Since all partition names are stored as strings in the metastore db, Hive discriminates between integer value ``1`` and ``01``, but Presto doesn't. 

I have two questions:
- Did you notice a significant difference in performance with your fix as retrieving all partitions may hurt performance for tables with a large number of partitions?
- Do you know whether this is still an issue with Hive 0.14?

**Comment by stagraqubole** [comment]
@nezihyigitbasi yes, there is a performance impact but the fix does not kick in every time. It affects only the cases where metastore returns empty list for getPartitionNamesByParts.

We haven't moved to Hive 0.14 yet, so haven't had a change to verify it there.

Also, the ideal fix would have been passing regex in partion name but it is not possible as special characters are escaped in this codepath. If hive 0.14 has a way to do it, we can have a fix without perf impact.

**Comment by cberner** [comment]
I think https://github.com/facebook/presto/pull/2244 should fix this. Please re-open, if not
