### ISSUE TITLE
JDBC Driver: Column type are flipped from Integer from BigInt

### ISSUE THREAD

**Issue by lucboudreau** [facebook/presto#3076]
This was observed with the MySQL connector. 

A column defined as an int(11), once read through Presto, comes back as JDBC Type -5 (BigInt).

**Comment by electrum** [comment]
This is expected, since the only integer type currently supported is bigint, so all integer types will be converted to that.

**Comment by electrum** [comment]
I'm going to close this for now since it is actually a Presto problem, not an issue with the JDBC driver. We have discussed adding smaller integer types and will likely do so in the future, at which we point we can support this in the MySQL connector (and then the JDBC driver will return the expected original type).
