### ISSUE TITLE
Jdbc Driver hardly usable w/ Apache DBCP

### ISSUE THREAD

**Issue by lucboudreau** [facebook/presto#3077]
When using Presto JDBC connections with Apache DBCP, some of the settings of DBCP will call into unimplemented methods which throw an error.

This is a deviation from the usual implementation guidelines. ie. setReadOnly can be called by the pool, but it is assumed that the driver will only throw an exception if there is a server error, *not* because it is not supported. See the API details here.

http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#setReadOnly(boolean)

This prevents us from using generic pool parameters and require knowledge of what will throw exception and what won't before using a generic set of parameters.

**Comment by electrum** [comment]
Is the issue calling it with `false`? If set to `false`, the driver throws `SQLFeatureNotSupportedException("Disabling read-only mode not supported")`. When the driver was originally written, Presto only supported `SELECT`, so this was correct, but it never got updated.

I filed https://github.com/facebook/presto/issues/3100 for this.

**Comment by electrum** [comment]
I created #3101 to fix the `setReadOnly()` issue by always ignoring the call. I don't think we can ignore other methods. For example, ignoring `setAutoCommit(false)` would be wrong, since an `INSERT` statement or similar would still commit at the end of the statement.

If there are other methods causing a problem with DBCP, please file a new issue for each one along with the parameter values, allowing us to evaluate and fix each one independently.

Thanks for helping us improve Presto!
