### ISSUE TITLE
Order By Desc on a column containing nulls values returns wrong results

### ISSUE THREAD

**Issue by mattsfuller** [facebook/presto#3218]
The default null ordering for desc should be nulls first. But it is doing nulls last.

Postgres:
```
tpch=# select * from (select cast(null as bigint) union all select 1) T order by 1 desc;
 int8 
------
     
    1
(2 rows)
```

Presto:
```
presto:tiny> select * from (select cast(null as bigint) union all select 1) T order by 1 desc;
 _col0 
-------
     1 
 NULL  
(2 rows)
```

**Comment by mattsfuller** [comment]
I just saw in another bug that null ordering may be implementation-defined if it's not specified. 
If that is the case and this is intentional, I can close. But it might be nice to match behavior of other DBs is there is some consistency that is implemented.

**Comment by electrum** [comment]
This is actually intentional. It is legal per the SQL specification for `<sort specification list>`:

> If `<null ordering>` is not specified, then an implementation-defined `<null ordering>` is implicit. The implementation-defined default for `<null ordering>` shall not depend on the context outside of `<sort specification list>`.

We always default to `NULLS LAST` because users generally do not want to see nulls. The most common use of `ORDER BY` in Presto is with `LIMIT`, so having nulls first would often result in a result set with all nulls, which is almost never what the user wants.

But we definitely should document this behavior.

**Comment by electrum** [comment]
The `<null ordering>` specification only arrived in SQL:2003, and like many things in the SQL specification, I'm guessing different existing implementations had varying behavior. Though it appears MySQL, PostgreSQL and Oracle all share the same default. SQL Server appears to always do nulls first and does not support explicit null ordering. Thus it seems we are the opposite of Microsoft :)
