### ISSUE TITLE
Adjust join order

### ISSUE THREAD

**Issue by yuananf** [facebook/presto#3364]
We got a problem recently, there are queries like below (these queries are generated by some BI tools and can hardly be changed):
```
SELECT * FROM
a
JOIN b ON 0 = 0
JOIN c ON c.id = a.id AND c.name = b.name
```
And they run very slowly (we enable distributed join), I think that they are equivalent to this query:
```
SELECT * FROM
c
JOIN a ON c.id = a.id
JOIN b ON c.name = b.name
```
And this one finished quickly.

My question is, is it possible to change the join order so that it can run quickly?

**Comment by electrum** [comment]
Ideally, the optimizer would be able to do that automatically based on statistics, but none of that infrastructure exists today. Hints are another approach, but that might not work here given that the query is generated. External hints for specific query shapes are another idea (Oracle has a feature like this).

One thing you can try now is creating a Presto view that does the join in the correct order, then exposing that view to the BI tool rather than the base tables.

**Comment by yuananf** [comment]
Thanks. 
My understanding is this work should be done in cost-based-optimizer, which is not available,  for now.

Unfortunately,

**Comment by yuananf** [comment]
@electrum 
Is it possible to write an optimizer to optimize this kind of query?
This kind of adjustment does not need table statistics, it just put the join criteria on the right place.
Any advice will be great help.
