### ISSUE TITLE
HostAddress may not test equal after Jackson serialization roundtrip

### ISSUE THREAD

**Issue by erichwang** [facebook/presto#3397]
Presto's HostAddress implementation does not round-trip properly when getting converted to and from String representation.

```java
HostAddress base = HostAddress.fromParts("[1111:2222:3333:4444:5555:6666:7777:8888]", 1234);
HostAddress hostAddress1 = HostAddress.fromParts(base.getHostText(), base.getPort());
HostAddress hostAddress2 = hostAddress.fromString(base.toString());
Assert.assertEquals(hostAddress1, hostAddress2);
```

This poses a problem because passing a HostAddress through Jackson serialization (which uses the string representation) can produce a HostAddress that will not test equal to the original.

**Comment by sogorkis** [comment]
I think the problem is with `equals/hashCode` methods which takes into account _hostname_, _port_ and _hasBracketlessColons_ flag.

`toString` method always prints brackets around IPv6 hostnames ("[1111:2222:3333:4444:5555:6666:7777:8888]:1234" in this case) and `getHostText()` returns hostname without those brackets ("1111:2222:3333:4444:5555:6666:7777:8888"). In example which you provided, both addresses are equal on _hostname_ and _port_ fields, but not on _hasBracketlessColons_.

As requireBracketsForIPv6() method is not used I would recommend to completely remove this flag from this class.

I can fix this and add some unit tests.

**Comment by erichwang** [comment]
yup, that's spot on @sogorkis, thanks for offering, but we already have a fix ready to go here =)
