### ISSUE TITLE
Queued query fails with "secondary queue failed" error

### ISSUE THREAD

**Issue by cberner** [facebook/presto#3423]
Creating a these queues and rules

```
"queues": {
    "user.${USER}": {
      "maxConcurrent": 2,
      "maxQueued": 5
    },
    "dashboard.${USER}": {
      "maxConcurrent": 1,
      "maxQueued": 1
    },
```

```
"rules": [
    {
      "source": "(?i).*dashboard.*",
      "queues": [
        "user.${USER}",
        "dashboard.${USER}",
        "global"
      ]
    },
    {
      "queues": [
        "user.${USER}",
        "global"
      ]
    }
```

and then submitting 3 queries from the same user and with source "dashboard" results in 1 running, 2 queued and one of the queued queries failed immediately with an exception when the first one finishes

```
java.lang.IllegalStateException: Entering secondary queue failed
	at com.facebook.presto.execution.QueuedExecution.start(QueuedExecution.java:74)
	at com.facebook.presto.execution.QueryQueue.lambda$new$90(QueryQueue.java:49)
	at com.facebook.presto.execution.QueryQueue$$Lambda$215/1727978933.apply(Unknown Source)
	at io.airlift.concurrent.AsyncSemaphore.submitTask(AsyncSemaphore.java:112)
	at io.airlift.concurrent.AsyncSemaphore.runNext(AsyncSemaphore.java:90)
	at io.airlift.concurrent.AsyncSemaphore.access$000(AsyncSemaphore.java:39)
	at io.airlift.concurrent.AsyncSemaphore$1.run(AsyncSemaphore.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sopel39** [comment]
Hi, I think I have found the bug. In `QueryQueue.reserve(...)` `getAndDecrement` was used instead of `decrementAndGet`. This caused more permits to be given than `maxQueuedQueries + maxConcurrentQueries`.

I also looked at the code to see if there can be other issues with: `Entering secondary queue failed`.
What if there are two queues:
```
    "user.${USER}": {
      "maxConcurrent": 2,
      "maxQueued": 2
    },
    "dashboard.${USER}": {
      "maxConcurrent": 1,
      "maxQueued": 1
    },
```
and we start two queries at the same time. It can be that for the moment both of them will queue themselves in `dashboard.${USER}`. In such case `Entering secondary queue failed` will be thrown even though one query could be started immediately and the second could wait in `dashboard.${USER}`. Should we care about such scenario?

**Comment by sopel39** [comment]
@cberner Do you think it's worth adding more tests for resource queues and perhaps some integration test?

**Comment by cberner** [comment]
Yes, although last time I looked it wasn't easy to test. However, it might be easier with the resource manager now. Take a look at the cluster memory manager tests

**Comment by sopel39** [comment]
@cberner You mean tests for ClusterMemoryManager. I have browsed through the code and I haven't noticed any tests that would explicitly test it. Could you point me to a right file? I understand you mean unit tests (not integration) for SqlQueueQueryManager?

**Comment by cberner** [comment]
I meant `TestMemoryManager.testClusterPools()`
