### ISSUE TITLE
Add support for binary literals

### ISSUE THREAD

**Issue by martint** [facebook/presto#3901]
Per the ANSI spec:

```
<binary string literal> ::= 
    X <quote> [ <space>... ] [ { <hexit> [ <space>... ] <hexit> [ <space>... ] }... ] <quote>
      [ { <separator> <quote> [ <space>... ] [ { <hexit> [ <space>... ]  <hexit> [ <space>... ] }... ] <quote> }... ]
<hexit> ::=
    <digit> | A | B | C | D | E | F | a | b | c | d | e | f
```

Additionally:

1) The sequence
```   
   <quote> [ <space>... ] { <hexit> [ <space>... ] <hexit> [ <space>... ] }... <quote>
```
is equivalent to the sequence
```
   <quote> { <hexit> <hexit> }... <quote>
```

2) The sequence
```
   <quote> { <hexit> <hexit> }... <quote> <separator>
   <quote> { <hexit> <hexit> }... <quote>
```
is equivalent to the sequence
```
   <quote> { <hexit> <hexit> }... { <hexit> <hexit> }... <quote>
```

3) The introductory 'X' may be represented either in upper case (as 'X') or in lower case (as 'x').
4) It is implementation-defined whether the declared type of a *binary string literal* is a fixed-length binary string type, a variable-length binary string type, or a binary large object string type.

**Comment by yangyangyyy** [comment]
this is Yang, I'll be joining the team (I'm in bootcamp now), may I claim this task? thanks

**Comment by yangyangyyy** [comment]
Martin:
can I have a clarification?

when you said "is equivalent .." , you removed the spaces.

so we are not allowing hex strings of the form      X'  a0  b0 c0 ff ' ? (i.e. only allow  X'a0b0c0ff' )

Thanks
yang

**Comment by martint** [comment]
I copied that straight from the spec, but what it means is that you can think of the one with spaces as if it didn't have any spaces. It doesn't mean that we don't support the version with spaces.

I don't think we need to support the one with separators at this point.

**Comment by yangyangyyy** [comment]
thanks. for the result, say given an input        "X'61' "  , do we want the resulting StringLiteral to hold "61" or "\u0061" (single letter "a")

**Comment by martint** [comment]
It shouldn't be a string literal. It should be a binary literal (which doesn't exist today, and should contain a byte array with the data)

**Comment by yangyangyyy** [comment]
hi Martin : I wrote the grammar definition part. it actually supports the full spec (including the separator). it's a bit tricky because of the separator support, so I was hoping to run it by you first.

the basic thought is that, we want to easily skip out the separator (comment and ws), using the parser's built-in ability, instead of having to pick out the comment in BinaryStringLiteralContext.getText(), in order to be able to skip out the separator, the resulting binary_string has to be a non-terminal/rule, instead of terminal. then the segments (e.g. 'ab 01 0f' ) become full terminals, and could overlap with the existing definition of STRING, so STRING has to be changed to a non-terminal, and AstBuilder has to make corresponding changes on STRING() calls.  the starting "X" of binaryStringLiteral overlaps with IDENTIFIER, so one extra option has to be added to identifier rule.


https://github.com/yangyangyyy/presto/commit/77be010df4952ed687df644a49953e065f71f77f#diff-b6133c98ceb3bc51fb1698a107e63ee8R535

this way in BinaryStringLiteral's children are nicely cleansed of separators

**Comment by martint** [comment]
Let's not add support for separators right now. We can consider adding it later. It's a weird feature that we don't support anywhere else at this time, so it's likely to break a bunch of things (query formatting, CLI editing, etc)

**Comment by yangyangyyy** [comment]
sounds good, I'll keep it as a token
