### ISSUE TITLE
Presto cassandra connector bug - 200 results only?!

### ISSUE THREAD

**Issue by bundlking** [facebook/presto#4014]
Configured presto v0.125 as one coordinator and 2 worker nodes on a 3 node cassandra cluster using Datastax autoclustering AMI. Simple count query consistently returns only 200 results in presto.

**cqlsh:**
[cqlsh 5.0.1 | Cassandra 2.2.3 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> select COUNT(*) FROM test3.users ;

 count
   299

(1 rows)

Warnings :
Aggregation query used without partition key

**presto:**
select count(*) from test3.users;
 _col0 
   200 
(1 row)

Query 20151121_030053_00021_dnzki, FINISHED, 1 node
Splits: 4 total, 4 done (100.00%)
0:00 [200 rows, 200B] [980 rows/s, 980B/s]

It is unclear to me if this is some kind of strange settings issue or a bug?

**Comment by picharras** [comment]
I Have same issue. Any idea? Thanks!

**Comment by picharras** [comment]
Hi, i found a solution, edit your cassandra.properties file and add this:
cassandra.limit-for-partition-key-select=NUMBER

Where NUMBER is the max result that you want!

Not elegant but works!

**Comment by bundlking** [comment]
Cheers for this - I ended up doing the same, definitely not an elegant solution, and documentation is woeful!

**Comment by nemothekid** [comment]
I started seeing this error as well after upgrading from 0.107 to 0.136. The `cassandra.limit-for-partition-key-select` wasn't needed in 0.107 and would scan the whole table (we have millions of partition keys in some cases).

It looks like to me, along the line somewhere, presto stopped using the token range scanner.

**Comment by nemothekid** [comment]
This is a bug with presto.

It looks like Cassandra 2.2, with the release of aggregates, the result of `SELECT count(*) FROM a.b LIMIT 200` changes.

In Cassandra <= 2.1, `SELECT count(*) FROM a.b LIMIT 200`, returned 200 (and did so rather quickly). In Cassandra >= 2.2, `SELECT count(*) FROM a.b LIMIT 200` returns the entire number of rows in the set.

The logic breaks down here in [CassandraSession.java:queryPartitionKeys](https://github.com/facebook/presto/blob/master/presto-cassandra/src/main/java/com/facebook/presto/cassandra/CassandraSession.java#L363):
```
ResultSetFuture countFuture;
        if (!fullPartitionKey) {
            final Select countAll = CassandraCqlUtils.selectCountAllFrom(tableHandle).limit(limitForPartitionKeySelect);
            countFuture = executeWithSession(schemaName, new SessionCallable<ResultSetFuture>() {
                @Override
                public ResultSetFuture executeWithSession(Session session)
                {
                    System.out.println(countAll.getQueryString());
                    return session.executeAsync(countAll);
                }
            });
        }
        else {
            // no need to count if partition key is completely known
            countFuture = null;
        }

        int limit = fullPartitionKey ? 1 : limitForPartitionKeySelect;
        final Select partitionKeys = CassandraCqlUtils.selectDistinctFrom(tableHandle, partitionKeyColumns);
        partitionKeys.limit(limit);
        partitionKeys.setFetchSize(fetchSizeForPartitionKeySelect);

        if (!fullPartitionKey) {
            addWhereClause(partitionKeys.where(), partitionKeyColumns, new ArrayList<>());
            ResultSetFuture partitionKeyFuture = executeWithSession(schemaName, new SessionCallable<ResultSetFuture>() {
                @Override
                public ResultSetFuture executeWithSession(Session session)
                {
                    return session.executeAsync(partitionKeys);
                }
            });

            long count = countFuture.getUninterruptibly().one().getLong(0);
            if (count == limitForPartitionKeySelect) {
                partitionKeyFuture.cancel(true);
                return null; // too much effort to query all partition keys
            }
            else {
                return partitionKeyFuture.getUninterruptibly();
            }
        }
```

Presto does a query `SELECT count(*) FROM a.b LIMIT 200`, and if the result is less than 200, does a partition split, but if its more than 200 uses the Token Partitioner. Given that Cassandra 2.2+ now returns entire size of the table, despite the limit, a value like 1,000,000 != 200, and presto uses the `partitionKeyFuture` which only queries 200 keys (because presto thinks there are less than 200 keys in the table, when they are really 1 million). 

Another side effect is that now PLANNING is really slow for large tables because Cassandra is now trying to count an entire table.
