### ISSUE TITLE
Unbounded varchar should not be serialized with length

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4532]
The fact that `varchar` is internally represented as `varchar(MAX_INT)` is an implementation detail that should not leak out and be permanently stored in external systems. It also breaks backwards compatibility with older clients, causes issues in clients that try to allocate a buffer of that size, etc.

**Comment by martint** [comment]
FWIW, there are no known clients that rely on the name of the type (other than the Java client, which was fixed to support the length parameter) or that would allocate space based on the value, since it's a new feature. Those clients will have to deal with the length parameter, anyway, since constant strings have a type parameterized with their length (e.g., select 'foo' returns varchar(3) for that column)

What's unfortunate is that we picked varchar originally to represent the unbounded version, given that it's not a valid type according to the standard.

**Comment by electrum** [comment]
I think max int is a bad choice of "unlimited" and if we're going to leak it everywhere, let's pick something more reasonable that can actually be supported. There's no way a 2GB string will work today or in the foreseeable future.

It's BS to say we support X when in reality the limit is much lower.

**Comment by electrum** [comment]
Another idea for now: hack TypeSignature to know about "varchar" and it's magic length and have special serialization for it.

**Comment by martint** [comment]
I think we're going to have to hack something for this release, but the underlying problem is that varchar(n) and varchar are two different types with the same name. There are a number of things we could do in the long term, but the one that probably fits the best is to introduce a new type (text, string or something like that) to replace it.

**Comment by damiencarol** [comment]
@martint maybe _string_ to be close to HIVE.
