### ISSUE TITLE
duplication of column ordering specification

### ISSUE THREAD

**Issue by the6campbells** [facebook/presto#4553]
A query which emits duplication of ordering terms will encounter an error.

select rank () over ( order by c1, c3, c3 ) from x.y.z

Error: Query failed (#20160215_152308_08739_tff7r): orderBy and orderings sizes don't match

**Comment by electrum** [comment]
This should be relatively easy to fix. Start by adding a test to AbstractTestQueries that reproduces it, then find out where it fails.

**Comment by harunurhan** [comment]
`orderings` is a hash map, whereas `orderBySymbols is a list and can contain duplicates.
```
ImmutableList.Builder<Symbol> orderBySymbols = ImmutableList.builder();
Map<Symbol, SortOrder> orderings = new HashMap<>();
```

I don't know how to handle this, first two things come to my mind are:

-  Ignore duplicate just perform the function (ImmutableSet can be used instead of ImmutableList for orderyBySymbols)
- Throw a specific exception for duplication with a message like "order by has duplicate columns"

@electrum

**Comment by jxiang** [comment]
@electrum @harunurhan I created a pull request. Could you please take a look?

**Comment by martint** [comment]
Fixed.
