### ISSUE TITLE
Json functions returns wrong value (null) when casting varchar to json is used.

### ISSUE THREAD

**Issue by kokosing** [facebook/presto#4558]
Json functions returns null, while it is expected to return value. It happens only when casting from varchar to json is used. I noticed that for json_array_length and json_array_contains. See below example usage:

```
presto:default> SELECT json_array_length(JSON '[1, 2, 3]');
 _col0 
-------
     3 
(1 row)
presto:default> SELECT json_array_length('[1, 2, 3]');
 _col0 
-------
     3 
(1 row)
presto:default> SELECT json_array_length(CAST('[1, 2, 3]' AS JSON));
 _col0 
-------
 NULL  
(1 row)
```

**Comment by haozhun** [comment]
We removed the old behavior of cast between JSON and VARCHAR. And replaced it with a system of CAST between JSON and primitive/structural types. The old behavior can be found in function `JSON_PARSE` and `JSON_FORMAT`.

* `CAST (JSON '5' as BIGINT)`
* `CAST (JSON '1.23' as BIGINT)`
* `CAST (JSON '"a"' as VARCHAR)`
* `CAST (JSON '[1,2,3]' as ARRAY<BIGINT>)`
* `CAST (JSON '["a", "b", "c"]' as ARRAY<VARCHAR>)`
* `CAST (JSON '{"a": 1}' as MAP<VARCHAR, BIGINT>)`

See #3197 (and related request for comments in mailing list), [release 0.116](https://prestodb.io/docs/current/release/release-0.116.html), [release 0.117](https://prestodb.io/docs/current/release/release-0.117.html), [release 0.122](https://prestodb.io/docs/current/release/release-0.122.html), [release 0.135](https://prestodb.io/docs/current/release/release-0.135.html).

Since release 0.117, new functions `JSON_PARSE`, `JSON_FORMAT` are introduced;
Since release 0.122, cast between `JSON` and `VARCHAR` throws exception instructing users to migrate.
Since release 0.136, new behavior of cast between `JSON` and `VARCHAR` is introduced along with other cast between `JSON` and primitive types.

**Comment by dain** [comment]
Instead of using a cast, use the [json_parse](https://prestodb.io/docs/current/functions/json.html#json_parse) function.  For example:
```
presto:default> SELECT json_array_length(json_parse('[1, 2, 3]'));
 _col0 
-------
     3 
(1 row)
```

**Comment by kokosing** [comment]
@haozhun, @dain Thanks, I am closing this issue.
